Update pr-title-verification.yml
Fix grep syntax

diff --git a/.github/workflows/pr-title-verification.yml b/.github/workflows/pr-title-verification.yml
--- a/.github/workflows/pr-title-verification.yml
+++ b/.github/workflows/pr-title-verification.yml
@@ -1,6 +1,6 @@
 # This is a basic workflow to help you get started with Actions
 
-name: PR
+name: PR check
 
 # Controls when the workflow will run
 on:
@@ -24,8 +24,9 @@ jobs:
       - name: Checking Title
         id: check-title
         run: |
-          echo '${{ github.event.pull_request.title }}'
-          [[ '${{ github.event.pull_request.title }}' =~ ^.*\PAB-[0-9]+|no-issue\.*$ ]] || [[ '${{ github.event.pull_request.description }}' =~ ^.*\PAB-[0-9]+|no-issue\.*$ ]] && exit 0 || echo "missing-id=true" >> $GITHUB_OUTPUT
+          echo 'Title - ${{ github.event.pull_request.title }}'
+          echo 'Description - ${{ github.event.pull_request.description }}'
+          [[ '${{ github.event.pull_request.title }}' =~ ^.*\[PAB-[0-9]+\]|\[no-issue\].*$ ]] || [[ '${{ github.event.pull_request.description }}' =~ ^.*\[PAB-[0-9]+\]|\[no-issue\].*$ ]] && exit 0 || echo "missing-id=true" >> $GITHUB_OUTPUT
       - name: Ticket id missing in PR title
         if: ${{ steps.check-title.outputs.missing-id == 'true' }}
         run: |
